version: "3.8"

services:
  iaxccm:
    image: ${DOCKER_IMAGE}
    container_name: xccm-iaxccm
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      LLM_SERVICE_URL: http://xccm-llm-service:8000
      BACKEND_URL: http://xccm-backend:8080
    networks:
      - xccm-network
    restart: always

networks:
  xccm-network:
    external: true
